[package]
name = "bevy-quinn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
quinn-proto = "0.11"
quinn-udp = "0.5"
bytes = "1"
rustls = "0.23"

# [dev-dependencies]
# rcgen = "0.13"
